version: 2.1

orbs:
  node: circleci/node@4.2.1

commands:
  install_node_modules:
    description: 'Install node modules'
    steps:
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            sudo corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install --no-frozen-lockfile
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

jobs:
  build:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - install_node_modules
      - run:
          name: Build
          command: pnpm build
      - run:
          name: Lint and Test
          command: pnpm run pre-commit

  deploy:
    executor:
      name: node/default
      tag: '16.18.0'
    steps:
      - checkout
      - install_node_modules
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_DEPLOY_TOKEN" --only hosting

workflows:
  build-and-deploy-main:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          context: learning-cicd-main
